PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX la: <https://linked.art/ns/terms/>
PREFIX schema: <https://schema.org/>

# Use a 'scrollable cursor' - https://vos.openlinksw.com/owiki/wiki/VOS/VirtTipsAndTricksHowToHandleBandwidthLimitExceed
SELECT *
WHERE {
  {
    SELECT ?this
    WHERE {
      ?this a schema:TextDigitalDocument .
        # la:member_of <https://data.colonialcollections.nl/nmvw/collection-archives> .
    }
  }
}
LIMIT ?_limit
OFFSET ?_offset
