PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX la: <https://linked.art/ns/terms/>

# Use a 'scrollable cursor' - https://vos.openlinksw.com/owiki/wiki/VOS/VirtTipsAndTricksHowToHandleBandwidthLimitExceed
SELECT *
WHERE {
  {
    SELECT ?this
    WHERE {
      ?this a ?type
      FILTER(?type IN (crm:E21_Person, crm:E74_Group, crm:E39_Actor))
    }
  }
}
LIMIT ?_limit
OFFSET ?_offset
